# Generated by Django 4.2.16 on 2024-10-10 11:14

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offenlage',
            fields=[
                ('generic_id', models.UUIDField(default=uuid.uuid4)),
                ('created', models.DateTimeField(null=True)),
                ('changed', models.DateTimeField(null=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('active', models.BooleanField(default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('offenlage_url', models.CharField(blank=True, max_length=300, null=True)),
                ('gkz', models.CharField(blank=True, max_length=300, null=True)),
                ('stadt', models.CharField(blank=True, max_length=300, null=True)),
                ('planart', models.IntegerField(blank=True, null=True)),
                ('rechtsstand', models.IntegerField(blank=True, null=True)),
                ('offenlage_beginn', models.DateField(blank=True, max_length=300, null=True, verbose_name='offenlage begin')),
                ('offenlage_ende', models.DateField(blank=True, max_length=300, null=True, verbose_name='offenlage ende')),
                ('kontakt', models.CharField(blank=True, max_length=2048, null=True)),
                ('notiz', models.CharField(blank=True, max_length=2048, null=True)),
                ('public', models.BooleanField(blank=True, default=True, null=True)),
                ('the_geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('typ_planart', models.CharField(choices=[('BPLAN', (('BPlan_10000', 'einfacher BPlan'), ('BPlan_10001', 'qualifizierter BPlan'), ("BPlan_2000'", 'BPlanNachParag13'), ('BPlan_3000', 'vorhabenbezogener BPlan'), ('BPlan_4000', 'Innenbereichssatzung'), ('BPlan_40000', 'Klarstellungssatzung'), ('BPlan_40001', 'Entwicklungssatzung'), ('BPlan_40002', 'Ergaenzungssatzung'), ('BPlan_5000', 'AussenbereichsSatzung'), ('BPlan_6000', 'BPlan_Innenentwicklung'), ('BPlan_7000', 'OertlicheBauvorschrift'), ('BPlan_9999', 'Sonstiges'))), ('FPLAN', (('FPlan_10000', 'FPlan'), ('FPlan_2000', 'GemeinsamerFPlan'), ("FPlan_3000'", 'RegFPlan'), ('FPlan_4000', 'FPlanRegPlan'), ('FPlan_5000', 'FPlanNachParag13')))], default='einfacher BPlan', max_length=300)),
                ('typ', models.CharField(blank=True, max_length=30, null=True)),
                ('offenlage_bekanntmachung', models.DateField(blank=True, max_length=300, null=True, verbose_name='Offenlage bekanntmachung')),
                ('uvp_vorpruefung', models.BooleanField(blank=True, default=True, null=True)),
                ('uvp', models.BooleanField(blank=True, default=True, null=True)),
                ('uvp_beginn', models.DateField(blank=True, max_length=300, null=True, verbose_name='uvp begin')),
                ('uvp_ende', models.DateField(blank=True, max_length=300, null=True, verbose_name='uvp ende')),
                ('uvp_kosten', models.FloatField(blank=True, null=True)),
                ('uvp_url', models.CharField(blank=True, max_length=2048, null=True)),
                ('owned_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
