"""
Django settings for blog project.

Generated by 'django-admin startproject' using Django 3.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-i*v31p2yevjkp7j#@grj+-qzuguwsm^(q4a)8#=rws9@wn%^=w'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
    "offenlage",
    "user",
    'crispy_forms',
    'django_tables2',
    'leaflet',
 
]    

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
CORS_ALLOW_ALL_ORIGINS = True  # Dikkat: bu ayar, tüm kaynaklardan erişime izin verir.
ROOT_URLCONF = 'blog.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ["templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'blog.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
     'default': {
     'ENGINE': 'django.contrib.gis.db.backends.postgis',
         'NAME': 'testgis',
         'USER':'postgres',
         'PASSWORD' : 'postgres',
         'HOST' : 'localhost',
         'PORT' : '5432'
 }}


# 'ENGINE': 'django.db.backends.postgresql',
# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'de-de'

TIME_ZONE = 'Europe/Berlin'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CRISPY_TEMPLATE_PACK = 'bootstrap4'






LEAFLET_CONFIG = {
    'DEFAULT_CENTER': (50.3563, 7.5886),
    'DEFAULT_ZOOM': 10,
    'SCALE': 'metric',
    'MIN_ZOOM': 3,
    'MAX_ZOOM': 18,
    
    'TILES': [
        # OpenStreetMap Base Layer
        ('OpenStreetMap', 
         'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', 
         {
             'attribution': '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
             'maxZoom': 18,
         }),
        # WMS Layer (RLP WMS)
        # ('RLP WMS', 
        #  'https://geo4.service24.rlp.de/wms/rp_dop20.fcgi?/{z}/{x}/{y}.png',
        #  {
        #      'layers': 'wms_rp_dop20',
        #      'format': 'image/png',
        #      'transparent': True,
        #      'attribution': 'RLP Geoportal WMS',
        #      'maxZoom': 18,
        #      'minZoom': 3,
        #      'CRS': 'EPSG:3857',
        #  })
    ],
    'CRS': 'EPSG:3857',  # Harita CRS'sini belirleme
    'DRAW': {
        'polyline': True,
        'polygon': True,
        'circle': True,
        'rectangle': True,
        'marker': True,
        'circlemarker': False,
    },
    'EDIT': {
        'featureGroup': True,
    },
    # 'PLUGINS': {
    #     'forms': {
    #         'auto-include': True
    #     }
    # }
}





DATE_FORMAT = ( ( 'Y-m-d' ))
DATE_INPUT_FORMATS = ( ('%Y-%m-%d'),)
DATETIME_FORMAT = (( 'Y-m-d H:i' ))
DATETIME_INPUT_FORMATS = (('%Y-%m-%d %H:%i'),)